name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  versionning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pre-rel.outputs.version }}
      release: ${{ steps.release.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Git magic
      run: |
        git checkout $(git rev-parse HEAD)
        git tag -d ${{ github.ref_name }}

    - name: Compute branch for codacy
      id: rev
      run: |
        export SHA=$(git rev-parse HEAD)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
        export CURRENT_BRANCH=$(git describe --tags)
        echo "current-branch=$CURRENT_BRANCH" >> $GITHUB_OUTPUT

    - name: Generate Pre-Release Version
      id: pre-rel
      uses: codacy/git-version@2.7.1
      with:
        minor-identifier: "feat:"
        release-branch: ${{ github.ref_name }}-pre
        dev-branch: ${{ steps.rev.outputs.current-branch }}

    - name: Generate Release Version
      id: release
      uses: codacy/git-version@2.7.1
      with:
        minor-identifier: "feat:"
        release-branch: ${{ steps.rev.outputs.current-branch }}
        dev-branch: main

    - name: Print version
      run: |
        echo PREREL ${{ steps.pre-rel.outputs.version }} >> $GITHUB_STEP_SUMMARY
        echo RELASE ${{ steps.release.outputs.version }} >> $GITHUB_STEP_SUMMARY

    - name: Validate tag
      run : test ${{ steps.release.outputs.version }} == ${{ github.ref_name }}

    - name: Delete tag
      if: failure() || cancelled()
      run : git push -d ${{ github.ref_name }}
