name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  versionning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pre-rel.outputs.version }}
      release: ${{ steps.release.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Git status
      run: |
        git status
        echo ${{ github.ref_name }}

    - name: Github metadata
      run: |
        echo ${{ github }}

    - name: Generate Pre-Release Version
      id: pre-rel
      uses: codacy/git-version@2.7.1
      with:
        minor-identifier: "feat:"
        release-branch: ${{ github.ref_name }}-pre
        dev-branch: ${{ github.ref_name }}

    - name: Generate Release Version
      id: release
      uses: codacy/git-version@2.7.1
      with:
        minor-identifier: "feat:"
        release-branch: ${{ github.ref_name }}
        dev-branch: main

    - name: Print version
      run: |
        echo PREREL ${{ steps.pre-rel.outputs.version }} >> $GITHUB_STEP_SUMMARY
        echo RELASE ${{ steps.release.outputs.version }} >> $GITHUB_STEP_SUMMARY
